# TDI PYTHON PROJECT WEEK THREE 
## Week 3: Exploring and Analyzing Data with Python 

### 1. Reading a Text File 
- Write a Python script that opens a file in read mode and prints its contents. 
- Use any .txt file for practice. 

In [2]:
# 1. Reading a Text File
try:
    file = open("output.txt", "r")
    text_content = file.read()
except FileNotFoundError:
    print("The file you want to read doesn't exist")
finally:
    file.close()

### 2. Writing to a File 
- Create a Python script that writes the string "Hello, Data Analysis!" to a new text file.

In [20]:
# 2. Writing to a File
file = open("output.txt", "w")
file.write("Hello, Data Analysis!")
print('File Creation Successful')
file.close()

File Creation Successful


### 3. Reading the Titanic Dataset (CSV) 
- Use the csv module to read the Titanic dataset (titanic.csv). 
- Print the first 5 rows of the dataset. 


In [19]:
# 3. Reading the Titanic Dataset
import csv
try:
    file = open("tdi_titanic_data.csv", "r")
    reader = csv.reader(file)
    for i, row in enumerate(reader):
        if i <= 5:
            print(row)
except FileNotFoundError:
    print("The file you want to read doesn't exist")
finally:
    file.close()

['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest']
['1', '1', 'Allen, Miss. Elisabeth Walton', 'female', '29', '0', '0', '24160', '211.3375', 'B5', 'S', '2', '', 'St Louis, MO']
['1', '1', 'Allison, Master. Hudson Trevor', 'male', '0.9167', '1', '2', '113781', '151.55', 'C22 C26', 'S', '11', '', 'Montreal, PQ / Chesterville, ON']
['1', '0', 'Allison, Miss. Helen Loraine', 'female', '2', '1', '2', '113781', '151.55', 'C22 C26', 'S', '', '', 'Montreal, PQ / Chesterville, ON']
['1', '0', 'Allison, Mr. Hudson Joshua Creighton', 'male', '30', '1', '2', '113781', '151.55', 'C22 C26', 'S', '', '135', 'Montreal, PQ / Chesterville, ON']
['1', '0', 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)', 'female', '25', '1', '2', '113781', '151.55', 'C22 C26', 'S', '', '', 'Montreal, PQ / Chesterville, ON']


### 4. Counting Records 
- After reading the Titanic CSV file, count the total number of passengers.

In [23]:
# 4. Counting Records
try:
    file = open("tdi_titanic_data.csv", "r")
    reader = list(csv.reader(file))
    total_passengers = len(reader) - 1
    print("Total passengers:", total_passengers)
except FileNotFoundError:
    print("The file you want to read doesn't exist")
finally:
    file.close()

Total passengers: 1309


### 5. Calculating Average Fare 
- Write a script to calculate the average fare paid by passengers using the Titanic dataset. 

In [30]:
# 5. Calculating Average Fare
fares = []
try:
    file = open("tdi_titanic_data.csv", "r")
    reader = csv.reader(file)
    next(reader)  # Skip header
    for row in reader:
        if row[8]:
            fares.append(float(row[8]))
            average_fare = sum(fares) / len(fares)
    print("Average Fare:", average_fare)
except FileNotFoundError:
    print("The file you want to read doesn't exist")
finally:
    file.close()

Average Fare: 33.29547928134572


### 6. Survivors by Class 
- Write a Python script to calculate the number of survivors per passenger class (1st, 2nd, and 3rd class).

In [ ]:
# 6. Survivor by class
survivors_by_class = {1: 0, 2: 0, 3: 0}
try:
    file = open("tdi_titanic_data.csv", "r")
    reader = csv.reader(file)
    next(reader)  # Skip header
    for row in reader:
        if row[0] == '1' and row[1] == '1':
            survivors_by_class[1] += 1
        elif row[0] == '2' and row[1] == '1':
            survivors_by_class[2] += 1
        elif row[0] == '3' and row[1] == '1':
            survivors_by_class[3] += 1
    print("Survivors by class:", survivors_by_class)
except FileNotFoundError:
    print("The file you want to read doesn't exist")
finally:
    file.close()

Survivors by class: {1: 200, 2: 119, 3: 181}


### Introduction to NumPy 
#### 7. NumPy Basics 
- Import the NumPy library and create a 1D array containing the following numbers: [10, 15, 20, 25]. Print the array. 

In [51]:
import numpy as np

In [52]:
# 7. NumPy Basics
arr = np.array([10, 15, 20, 25])
print("NumPy Array:", arr)

NumPy Array: [10 15 20 25]


### 8. Array Operations 
- Using the array from the previous question, perform the following operations: 

    • Multiply each element by 2. 
    
    • Subtract 5 from each element. 

In [54]:
# 8. Array Operations
arr_multiplied = arr * 2
arr_subtracted = arr_multiplied - 5
print("Array x2:", arr_multiplied)
print("Array -5:", arr_subtracted)

Array x2: [20 30 40 50]
Array -5: [15 25 35 45]


### 9. 2D Array Creation 
- Create a 2D NumPy array with shape (3, 3) using the following data: 

    • First row: 1, 2, 3 

    • Second row: 4, 5, 6 
    
    • Third row: 7, 8, 9 

In [57]:
# 9. 2D NumPy Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array: \n", arr_2d)

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 10. Titanic Data with NumPy 
- Convert the Fare column of the Titanic dataset to a NumPy array and calculate: 

    • The minimum fare. 

    • The maximum fare.
     
    • The mean fare. 


In [61]:
# 10. Titanic Fare Stats
fares_np = np.array(fares)
min_fare = fares_np.min()
max_fare = fares_np.max()
mean_fare = fares_np.mean()


print("Min Fare:", min_fare)
print("Max Fare:", max_fare) 
print("Mean Fare:", mean_fare)

Min Fare: 0.0
Max Fare: 512.3292
Mean Fare: 33.29547928134557


### 11. Array Indexing 
- Use array indexing to extract the first row and first column of the 2D array created earlier. Print the results. 

In [62]:
# 11. Array Indexing
first_row = arr_2d[0]
first_column = arr_2d[:, 0]
print("First Row:", first_row)
print("First Column:", first_column)

First Row: [1 2 3]
First Column: [1 4 7]


### 12. Random Array 
- Create a NumPy array with 10 random numbers between 0 and 1. Print the array and find the maximum value. 

In [63]:
# 12. Random Array
random_arr = np.random.rand(10)
max_random_value = random_arr.max()
print("Random Array:", random_arr)
print("Max Value:", max_random_value)

Random Array: [0.62965607 0.61661871 0.59302344 0.12481364 0.46365301 0.46962299
 0.5338354  0.97418492 0.81126321 0.44761989]
Max Value: 0.9741849167320834


### 13. Survivor Analysis with NumPy 
- Use the Titanic dataset and convert the Survived column to a 
NumPy array. 
- Calculate the percentage of passengers who survived. 

In [64]:
# 13. Survivor Percentage
survived = []
file = open("tdi_titanic_data.csv", "r")
reader = csv.reader(file)
next(reader)
for row in reader:
    survived.append(int(row[1]))
file.close()
survival_rate = (sum(survived) / len(survived)) * 100
print("Survival Rate:", survival_rate, "%")

Survival Rate: 38.19709702062643 %
